import { Info, Lightbulb, OctagonAlert, TriangleAlert } from "lucide-react";

import type { AIBlock, Insight } from "@/lib/api-types";
import { formatMoney } from "@/lib/format";

type SeverityStyle = {
  border: string;
  text: string;
  icon: typeof Info;
};

function severityStyle(severity: Insight["severity"]): SeverityStyle {
  switch (severity) {
    case "critical":
      return { border: "border-destructive/50", text: "text-destructive", icon: OctagonAlert };
    case "warn":
      return { border: "border-amber-400/50", text: "text-amber-400", icon: TriangleAlert };
    case "info":
    default:
      return { border: "border-primary/40", text: "text-primary", icon: Info };
  }
}

export function InsightsPanel({ ai }: { ai: AIBlock }) {
  const hasInsights = ai.insights.length > 0;
  const hasRecommendations = ai.recommendations.length > 0;

  return (
    <div className="space-y-5">
      <div className="glass-card rounded-2xl p-5">
        <h3 className="mb-2 text-sm font-semibold text-foreground">Summary</h3>
        <p className="leading-relaxed text-muted-foreground">
          {ai.summary || "No summary available for this period."}
        </p>
      </div>

      <div>
        <h3 className="mb-3 text-sm font-semibold text-foreground">Insights</h3>
        {hasInsights ? (
          <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
            {ai.insights.map((insight, i) => {
              const style = severityStyle(insight.severity);
              const Icon = style.icon;
              return (
                <div
                  key={`${insight.title}-${i}`}
                  className={`glass-card rounded-xl border ${style.border} p-4`}
                >
                  <div className="mb-1 flex items-center gap-2">
                    <Icon className={`size-4 ${style.text}`} />
                    <span className="font-semibold text-foreground">{insight.title}</span>
                  </div>
                  <p className="text-sm text-muted-foreground">{insight.detail}</p>
                </div>
              );
            })}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">No insights for this period.</p>
        )}
      </div>

      <div>
        <h3 className="mb-3 text-sm font-semibold text-foreground">Recommendations</h3>
        {hasRecommendations ? (
          <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
            {ai.recommendations.map((rec, i) => (
              <div
                key={`${rec.title}-${i}`}
                className="glass-card flex flex-col gap-2 rounded-xl border border-border p-4"
              >
                <div className="flex items-center gap-2">
                  <Lightbulb className="size-4 text-primary" />
                  <span className="font-semibold text-foreground">{rec.title}</span>
                </div>
                <p className="text-sm text-muted-foreground">{rec.detail}</p>
                {rec.estimated_monthly_savings != null && (
                  <span className="num-mono inline-flex w-fit items-center rounded-full bg-success/15 px-2.5 py-0.5 text-xs font-semibold text-success">
                    Save ~{formatMoney(rec.estimated_monthly_savings)}/mo
                  </span>
                )}
              </div>
            ))}
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">No recommendations for this period.</p>
        )}
      </div>

      <p className="text-xs text-muted-foreground">Generated by {ai.model}</p>
    </div>
  );
}

export default InsightsPanel;
